SELECT USER
FROM DUAL;
--==>> SCOTT 2022-11-15

--°€ Ω«Ω¿ ≈◊¿Ã∫Ì ª˝º∫ (¡ˆø™:REGION)
CREATE TABLE REGION
( REGIONID  NUMBER                  -- ¡ˆø™ æ∆¿Ãµ   - PK
, REGIONNAME VARCHAR2(30)           -- ¡ˆø™ ¿Ã∏ß
, CONSTRAINT REGION_ID_PK PRIMARY KEY(REGIONID)
);
--==>>Table REGION¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.


--°€Ω√ƒˆΩ∫ ª˝º∫
CREATE SEQUENCE REGIONSEQ
NOCACHE;
--==>> Sequence REGIONSEQ¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

--°€ µ•¿Ã≈Õ ¿‘∑¬ (¡ˆø™ µ•¿Ã≈Õ ¿‘∑¬)
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'º≠øÔ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¿Œ√µ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¥Î±∏');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'±§¡÷');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¥Î¿¸');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'∫ŒªÍ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'øÔªÍ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'∞Ê±‚');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'∞≠ø¯');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'√Ê∫œ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'√Ê≥≤');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¿¸∫œ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¿¸≥≤');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'∞Ê∫œ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'∞Ê≥≤');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¡¶¡÷');
--==>> 1 «‡ ¿Ã(∞°) ª¿‘µ«æ˙Ω¿¥œ¥Ÿ. * 16

--°€ »Æ¿Œ
SELECT REGIONID, REGIONNAME
FROM REGION;
/*
1	º≠øÔ
2	¿Œ√µ
3	¥Î±∏
4	±§¡÷
5	¥Î¿¸
6	∫ŒªÍ
7	øÔªÍ
8	∞Ê±‚
9	∞≠ø¯
10	√Ê∫œ
11	√Ê≥≤
12	¿¸∫œ
13	¿¸≥≤
14	∞Ê∫œ
15	∞Ê≥≤
16	¡¶¡÷
*/
--°€ ƒøπ‘
COMMIT;
--==>> ƒøπ‘ øœ∑·.

--°€ Ω«Ω¿ ≈◊¿Ã∫Ì ª˝º∫(¡˜¿ß : POSITION)
CREATE TABLE POSITION
( POSITIONID    NUMBER          -- ¡˜¿ß æ∆¿Ãµ -- pk
, POSITIONNAME  VARCHAR2(30)    -- ¡˜¿ß ¿Ã∏ß
, MINBASICPAY   NUMBER          -- «ÿ¥Á ¡˜¿ß¿« √÷º“ ±‚∫ª±ﬁ
, CONSTRAINT POSITION_ID_PK PRIMARY KEY(POSITIONID)
);
--==>> Table POSITION¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

--°€ Ω√ƒˆΩ∫ ª˝º∫( ¡˜¿ß : POSITIONSEQ)
CREATE SEQUENCE POSITIONSEQ
NOCACHE;
--==>> Sequence POSITIONSEQ¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

--°€ µ•¿Ã≈Õ ¿‘∑¬ (¡˜¿ß µ•¿Ã≈Õ ¿‘∑¬)
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, 'ªÁø¯', 1000000); -- πÈ∏∏
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '¥Î∏Æ', 2000000); -- ¿ÃπÈ∏∏
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '∞˙¿Â', 3000000); -- ªÔπÈ∏∏
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '∫Œ¿Â', 4000000); -- ªÁπÈ∏∏
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, 'ªÛπ´', 5000000); -- ø¿πÈ∏∏
--==>> 1 «‡ ¿Ã(∞°) ª¿‘µ«æ˙Ω¿¥œ¥Ÿ. * 5

--°€ »Æ¿Œ
SELECT POSITIONID, POSITIONNAME, MINBASICPAY
FROM POSITION;
/*
1	ªÁø¯	1000000
2	¥Î∏Æ	2000000
3	∞˙¿Â	3000000
4	∫Œ¿Â	4000000
5	ªÛπ´	5000000
*/

--°€ ƒøπ‘
COMMIT;
--==>> ƒøπ‘ øœ∑·.

-- ¡˜¿ß µ•¿Ã≈Õ ¿‘∑¬
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY) VALUES(POSITIONSEQ.NEXTVAL, 'ªÛπ´', 5000000)
;




--°€ Ω«Ω¿ ≈◊¿Ã∫Ì ª˝º∫(∫Œº≠ : DEPARTMENT_
CREATE TABLE DEPARTMENT
( DEPARTMENTID  NUMBER              -- ∫Œº≠ æ∆¿Ãµ   --PK
, DEPARTMENTNAME    VARCHAR2(30)    -- ∫Œº≠ ¿Ã∏ß
, CONSTRAINT DEPARTMENT_ID_PK PRIMARY KEY(DEPARTMENTID)
);
--==>> Table DEPARTMENT¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.


--°€Ω√ƒˆΩ∫ ª˜º∫(∫Œº≠ : DRPARTMENTSEQ)
CREATE SEQUENCE DEPARTMENTSEQ
NOCACHE;
--==>> Sequence DEPARTMENTSEQ¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

--°€ µ•¿Ã≈Õ ¿‘∑¬ (∫Œº≠ µ•¿Ã≈Õ ¿‘∑¬)
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'∞≥πﬂ∫Œ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'±‚»π∫Œ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'øµæ˜∫Œ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'¿ŒªÁ∫Œ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'ªÁæ˜∫Œ');
--==>> 1 «‡ ¿Ã(∞°) ª¿‘µ«æ˙Ω¿¥œ¥Ÿ.


--°€ »Æ¿Œ
SELECT DEPARTMENTID, DEPARTMENTNAME
FROM DEPARTMENT;
/*
1	∞≥πﬂ∫Œ
2	±‚»π∫Œ
3	øµæ˜∫Œ
4	¿ŒªÁ∫Œ
5	ªÁæ˜∫Œ
*/

--°€ ƒøπ‘
COMMIT;
--==>> ƒøπ‘ øœ∑·.


--°€ Ω«Ω¿ ≈◊¿Ã∫Ì ª˝º∫(¡˜ø¯ : EMPLOYEE)
-- ªÁø¯π¯»£, ªÁø¯∏Ì, ¡÷πŒπ¯»£, ª˝≥‚ø˘¿œ, æÁ¿Ω∑¬, ¿¸»≠π¯»£, ∫Œº≠, ¡˜¿ß, ¡ˆø™, ±‚∫ª±ﬁ, ºˆ¥Á (11∞≥)
CREATE TABLE EMPLOYEE
( EMPLOYEEID    NUMBER              -- ªÁø¯ π¯»£     --PK
, NAME          VARCHAR2(30)        -- ªÁø¯ ¿Ã∏ß
, SSN           VARCHAR2(20)        -- ¡÷πŒ π¯»£        -- æœ»£»≠ ±‚¥… ¿˚øÎ(≈∏¿‘ CHECK~!!)
, BIRTHDAY      DATE                -- ª˝≥‚ ø˘¿œ
, LUNAR         NUMBER(1) DEFAULT 0 -- æÁ¿Ω∑¬        -- æÁ∑¬0, ¿Ω∑¬1
, TELEPHONE     VARCHAR2(40)        -- ¿¸»≠π¯»£
, DEPARTMENTID  NUMBER              -- ∫Œº≠ æ∆¿Ãµ   -- FK
, POSITIONID    NUMBER              -- ¡˜¿ß æ∆¿Ãµ   -- FK
, REGIONID      NUMBER              -- ¡ˆø™ æ∆¿Ãµ   -- FK
, BASICPAY      NUMBER              -- ±‚∫ª±ﬁ
, EXTRAPAY      NUMBER              -- ºˆ¥Á
, CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYEEID)
, CONSTRAINT EMPLOYEE_DEPARMENTID_FK FOREIGN KEY(DEPARTMENTID)
            REFERENCES DEPARTMENT(DEPARTMENTID)
, CONSTRAINT EMPLOYEE_POSITION_FK FOREIGN KEY(POSITIONID)
            REFERENCES POSITION(POSITIONID)
, CONSTRAINT EMPLOYEE_REGIONID_FK FOREIGN KEY(REGIONID)
            REFERENCES REGION(REGIONID)
, CONSTRAINT EMPLOYEE_LUNAR_CK CHECK(LUNAR=0 OR LUNAR=1)

);
--==>> Table EMPLOYEE¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.



--°€ Ω√ƒˆΩ∫ ª˝º∫
CREATE SEQUENCE EMPLOYEESEQ
NOCACHE;
--==>> Sequence EMPLOYEESEQ¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.



--°€  µ•¿Ã≈Õ ¿‘∑¬(¡˜ø¯ µ•¿Ã≈Õ ¿‘∑¬)
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'æˆº“ø¨', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567')
        , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000  );
--==>> 1 «‡ ¿Ã(∞°) ª¿‘µ«æ˙Ω¿¥œ¥Ÿ.

INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY) VALUES ( EMPLOYEESEQ.NEXTVAL,'æˆº“ø¨', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567') , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000)
;



-- »Æ¿Œ
SELECT *
FROM EMPLOYEE;
/*
EMPLOYEEID, NAME, SSN,     BIRTHDAY,  LUNAR, TELEPHONE,  DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY
----------------------------------------------------------------------------------------------------------
  1	     æˆº“ø¨	 ?`??$?	1994-11-24	0	010-7193-4562	1       	1	          1	    1500000	   1500000
*/
-- ¡˜ø¯ ¡§∫∏ ºˆ¡§ ƒı∏ÆπÆ ±∏º∫ æÓ∑∆¥Ÿ........


/* øœº∫«ÿ∫∏±‚...,,
UPDATE EMPLOYEE
SET NAME = π›∫∏øµ, TO_CHAR(2022-11-11, 'YYYY-MM-DD), LUNAR = 0,TELEPHONE = 010-9999-9999, DEPARTMENTID=1
, POSITIONID = 1, REGIONID = 7, BASICPAY = 2000000, EXTRAPAY= 1500000, GRADE=1
WHERE EMPLOYEEID = 1;
*/



-- °€ ƒøπ‘
COMMIT;
--==>> ƒøπ‘ øœ∑·.

--°€ ¡˜ø¯ ¡§∫∏ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, 'æÁ∑¬', 1, '¿Ω∑¬') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID= E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;

--°€ ∫‰ ª˝º∫ (EMPLOYEEVIEW)
CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, 'æÁ∑¬', 1, '¿Ω∑¬') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID= E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;
--==>> View EMPLOYEEVIEW¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

--°€ »Æ¿Œ
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, LUNARNAME, TELEPHONE, DEPARTMENTID, DEPARTMENTNAME, POSITIONID, POSITIONNAME, REGIONID, REGIONNAME, BASICPAY, EXTRAPAY, PAY, GRADE FROM EMPLOYEEVIEW
;

-- ¡˜ø¯ µ•¿Ã≈Õ ªË¡¶ ƒı∏ÆπÆ ±∏º∫
DELETE
FROM EMPLOYEEVIEW
WHERE EMPLOYEEID = 1;

DELETE FROM EMPLOYEEVIEW WHERE EMPLOYEEID = 1
;


ROLLBACK;



UPDATE EMPLOYEE
SET NAME = ? 
WHERE EMPLOYEEID=1;




SELECT * FROM EMPLOYEEVIEW
;
/*
1	æˆº“ø¨	?`??$?	1994-11-24	0	æÁ∑¬	010-7193-4562	1	∞≥πﬂ∫Œ	1	ªÁø¯	1	º≠øÔ	1500000	1500000	3000000
*/

--°€ ¡ˆø™ ¡§∫∏ ¡∂»∏ ƒ˚∏ÆπÆ ±∏º∫
--  (∆Ø¡§ ¡ˆø™ µ•¿Ã≈Õ ªË¡¶ ∞°¥…ø©∫Œ »Æ¿Œ)
SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;
/*
1	º≠øÔ	1
2	¿Œ√µ	0
    :
14	∞Ê∫œ	0
15	∞Ê≥≤	0
16	¡¶¡÷	0
*/
--> °∫º≠øÔ°ª¿« ¡ˆø™ ¡§∫∏¥¬ ªË¡¶∞° ∫“∞°¥…«— µ•¿Ã≈Õ¿Ã∏Á,
-- ±◊ ø‹ ≥™∏”¡ˆ ¡ˆø™ ¡§∫∏¥¬ ªË¡¶∞° ∞°¥…«— µ•¿Ã≈Õ¿”¿ª ∆«∫∞«“ ºˆ ¿÷∂«∑œ ±∏º∫«— ƒı∏ÆπÆ


--°ÿ ∫‰ ª˝º∫(¡ˆø™ ¡§∫∏ : REGIONVIEW)
CREATE OR REPLACE VIEW REGIONVIEW
AS
SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;
--==>> View REGIONVIEW¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

SELECT REGIONID, REGIONNAME, DELCHECK
FROM REGIONVIEW;

SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW
;

--°€ ¡˜¿ß ¡§∫∏ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
--  (∆Ø¡§ ¡˜¿ß µ•¿Ã≈Õ ªË¡¶ ∞°¥…ø©∫Œ »Æ¿Œ)

SELECT P.POSITIONID AS POSITIONID
      , P.POSITIONNAME AS POSITIONNAME
      , P.MINBASICPAY AS MINBASICPAY
      ,( SELECT COUNT(*)
         FROM EMPLOYEE
         WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;


--°ÿ ∫‰ ª˝º∫(¡ˆø™ ¡§∫∏ : POSITIONVIEW)
CREATE OR REPLACE VIEW POSITIONVIEW
AS
SELECT P.POSITIONID AS POSITIONID
      , P.POSITIONNAME AS POSITIONNAME
      , P.MINBASICPAY AS MINBASICPAY
      ,( SELECT COUNT(*)
         FROM EMPLOYEE
         WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;
--==>> View POSITIONVIEW¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM POSITIONVIEW;

SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW
;


--°€ ∫Œº≠ ¡§∫∏ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
--  (∆Ø¡§ ∫Œº≠ µ•¿Ã≈Õ ªË¡¶ ∞°¥…ø©∫Œ »Æ¿Œ)

SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    , (SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;

--°ÿ ∫‰ ª˝º∫( ¡§∫∏ : DEPARTMENTVIEW)
CREATE OR REPLACE VIEW DEPARTMENTVIEW
AS
SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    , (SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;
--==>> View DEPARTMENTVIEW¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.


-- ∫Œº≠ ¿¸√º µ•¿Ã≈Õ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK
FROM DEPARTMENTVIEW
ORDER BY DEPARTMENTID;
/*
1	∞≥πﬂ∫Œ	1
2	±‚»π∫Œ	0
3	øµæ˜∫Œ	0
4	¿ŒªÁ∫Œ	0
5	ªÁæ˜∫Œ	0
*/

--> «—¡Ÿ ±∏º∫
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK FROM DEPARTMENTVIEW ORDER BY DEPARTMENTID
;

--∫Œº≠ µ•¿Ã≈Õ ªË¡¶ ƒı∏ÆπÆ ±∏º∫ (∫Œº≠ π¯»£∑Œ ∫Œº≠ µ•¿Ã≈Õ ªË¡¶)
DELETE
FROM DEPARTMENT
WHERE DEPARTMENTID = 1;
--> «—¡Ÿ ±∏º∫
DELETE FROM DEPARTMENT WHERE DEPARTMENTID = 1
;
-- ∫Œº≠ µ•¿Ã≈Õ ºˆ¡§ ƒı∏ÆπÆ (∫Œº≠ π¯»£∑Œ ∫Œº≠ ¿Ã∏ß ∫Ø∞Ê)
UPDATE DEPARTMENT
SET DEPARTMENTNAME = '√—π´∫Œ'
WHERE DEPARTMENTID = 1;

--> «—¡Ÿ ±∏º∫

UPDATE DEPARTMENT SET DEPARTMENTNAME = '√—π´∫Œ' WHERE DEPARTMENTID = 1
;
--==>> 1 «‡ ¿Ã(∞°) æ˜µ•¿Ã∆Æµ«æ˙Ω¿¥œ¥Ÿ.


SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW ORDER BY REGIONID;

SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, LUNARNAME , TELEPHONE, DEPARTMENTID, DEPARTMENTNAME, POSITIONID , POSITIONNAME, REGIONID, REGIONNAME, BASICPAY, EXTRAPAY, PAY, GRADE FROM EMPLOYEEVIEW ORDER BY EMPLOYEEID
;

-- EMPLOYEE ≈◊¿Ã∫Ì ¡∂»∏ ƒı∏ÆπÆ
SELECT EMPLOYEEID, NAME, SSN1, TO_CHAR(BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID , POSITIONID, REGIONID, BASICPAY, EXTRAPAY FROM EMPLOYEE WHERE EMPLOYEEID = 1
;


ROLLBACK;


-- ¡ˆø™ ¿¸√º µ•¿Ã≈Õ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT REGIONID, REGIONNAME
FROM REGIONVIEW
ORDER BY REGIONID; 
/*
1	º≠øÔ
2	¿Œ√µ
3	¥Î±∏
4	±§¡÷
5	¥Î¿¸
6	∫ŒªÍ
7	øÔªÍ
8	∞Ê±‚
9	∞≠ø¯
10	√Ê∫œ
11	√Ê≥≤
12	¿¸∫œ
13	¿¸≥≤
14	∞Ê∫œ
15	∞Ê≥≤
16	¡¶¡÷
*/

SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW ORDER BY REGIONID
;


--¡ˆø™ µ•¿Ã≈Õ ªË¡¶ ƒı∏ÆπÆ ±∏º∫ (¡ˆø™ π¯»£∑Œ ∫Œº≠ µ•¿Ã≈Õ ªË¡¶)
DELETE
FROM REGION
WHERE REGIONID = 1;
--> «—¡Ÿ ±∏º∫
DELETE FROM REGION WHERE REGIONID = 1
;

--¡ˆø™ µ•¿Ã≈Õ ºˆ¡§ ƒı∏ÆπÆ ±∏º∫ (¡ˆø™ π¯»£ø¿ ¡ˆø™ ¿Ã∏ß ∫Ø∞Ê)

UPDATE REGION
SET REGIONNAME = '¡ˆø™∏Ì'
WHERE REGIONID = 1;
--> «—¡Ÿ ±∏º∫

UPDATE REGION SET REGIONNAME = '¡ˆø™∏Ì' WHERE REGIONID = 1
;
--==>> 1 «‡ ¿Ã(∞°) æ˜µ•¿Ã∆Æµ«æ˙Ω¿¥œ¥Ÿ.

ROLLBACK;
--==>> ∑—πÈ øœ∑·.

-- ¡˜¿ß ¿¸√º µ•¿Ã≈Õ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫

SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK
FROM POSITIONVIEW
ORDER BY POSITIONID;

--> «— ¡Ÿ ±∏º∫
SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW ORDER BY POSITIONID
;
/*
1	ªÁø¯	1000000	1
2	¥Î∏Æ	2000000	0
3	∞˙¿Â	3000000	0
4	∫Œ¿Â	4000000	0
5	ªÛπ´	5000000	0
*/

--¡˜¿ß µ•¿Ã≈Õ ªË¡¶ ƒı∏ÆπÆ ±∏º∫ (¡˜¿ß π¯»£∑Œ ¡˜¿ß µ•¿Ã≈Õ ªË¡¶)

DELETE
FROM POSITION
WHERE POSITIONID = 1;
--> «— ¡Ÿ ±∏º∫

DELETE FROM POSITION WHERE POSITIONID = 1
;

--¡˜¿ß µ•¿Ã≈Õ ºˆ¡§ ƒı∏ÆπÆ ±∏º∫ (¡˜¿ß π¯»£∑Œ ¡˜¿ß ¿Ã∏ß ∫Ø∞Ê)
   
UPDATE POSITION
SET POSITIONNAME = '¡˜¿ß∏Ì'
    , MINBASICPAY = 300000
WHERE POSITIONID = 1;
--> «— ¡Ÿ ±∏º∫
UPDATE POSITION SET POSITIONNAME = '¡˜¿ß∏Ì' , MINBASICPAY = 300000 WHERE POSITIONID = 1
;
--==> 1 «‡ ¿Ã(∞°) æ˜µ•¿Ã∆Æµ«æ˙Ω¿¥œ¥Ÿ.

ROLLBACK;
--==>> ∑—πÈ øœ∑·.

SELECT MINBASICPAY
FROM POSITION
WHERE POSITIONID = 1;


SELECT MINBASICPAY FROM POSITION WHERE POSITIONID = 1
;



--------------------------------------------------------------------------------
--°·°·°· ∑Œ±◊¿Œ/ ∑Œ±◊æ∆øÙ ±‚¥… ¿˚øÎ ∞˙¡§ √ﬂ∞°°·°·°·--

-- «ˆ¿Á øÏ∏Æ∞° ±∏º∫«— µ•¿Ã∫Ì ±∏¡∂¥¬ ID øÕ PW ƒ√∑≥ ¡§∫∏∏¶ ¥„∞Ì¿÷¥¬ µ•¿Ã∫Ì¿Ã 
-- ∫∞µµ∑Œ ¡∏¿Á«œ¡ˆ æ ¥¬ ªÛ»≤¿Ã¥Ÿ.
-- ¿ÃøÕ ∞¸∑√«œø© EMPLOYEE(ªÁø¯ æ∆¿Ãµ)øÕ SSN(¡÷πŒπ¯»£) µﬁ¿⁄∏Æ 7¿⁄∏Æ¿« º˝¿⁄∏¶
-- »∞øÎ∂Ûø© ±‚¥…¿ª ±∏«ˆ«“ ºˆ ¿÷µµ∑œ √≥∏Æ«—¥Ÿ.

-- °ÿ ±‚¡∏ µ•¿Ã∫Ì ±∏¡∂ ∫Ø∞Ê ∞Ë»π
-- ®Á
-- EMPLOYEE (¡˜ø¯ µ•¿Ã≈Õ µ•¿Ã∫Ì) ¿« SSN(¡÷πŒπ¯»£) ƒ√∑≥¿ª ∫–∏Æ«—¥Ÿ.
-- SSN   -------------> SSN1, SSN2
-- SSN1 --------------> ¡÷πŒπ¯»£ æ’ 6¿⁄∏Æ
-- SSN2 --------------> ¡÷πŒπ¯»£ µﬁ 7¿⁄∏Æ °Ê æœ»£»≠ ¿˚øÎ

--®Ë
-- EMPLOYEE (¡˜ø¯ µ•¿Ã≈Õ µ•¿Ã∫Ì)¿« GEADE(µÓ±ﬁ) ƒ√∑≥¿ª √ﬂ∞°«—¥Ÿ.
-- GRADE --------------> ∞¸∏Æ¿⁄0, ¿œπ›ªÁø¯1


-- °ÿ ±‚¡∏ µ•¿Ã∫Ì ±∏¡∂ ∫Ø∞Ê ºˆ«‡

--®Á-1. ƒ√∑≥ √ﬂ∞°
ALTER TABLE EMPLOYEE
ADD(SSN1 CHAR(6), SSN2 VARCHAR2(50));
--==>> Table EMPLOYEE¿Ã(∞°) ∫Ø∞Êµ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM EMPLOYEE;

-- ®Á-2. ±‚¡∏ µ•¿Ã≈Õø° ¥Î«ÿ ƒ√∑≥¿« ≥ªøÎ ºˆ¡§
-- '9411242234567'
/*
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'æˆº“ø¨', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567')
        , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000  );
*/
---------------------------------≥ª∞° «— ∞Õ
UPDATE EMPLOYEE
SET SSN1 = SUBSTR(1,6)
WHERE SSN;

SELECT CRYPTPACK.DECRYPT('9411242234567','9411242234567')
FROM EMPLOYEE;

UPDATE EMPLOYEE
SET SSN1 = SUBSTR(SSN, 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(SSN, 7,7) , SUBSTR(SSN, 7,7));
WHERE SSN

----------------------------------------------- º±ª˝¥‘¿Ã «œΩ≈∞Õ
SELECT CRYPTPACK.DECRYPT(SSN, '9411242234567')
FROM EMPLOYEE;
--==>>9411242234567

UPDATE EMPLOYEE
SET SSN1 = SUBSTR(¿‘∑¬≥ªøÎ, 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(¿‘∑¬≥ªøÎ, 7,7) , SUBSTR(¿‘∑¬≥ªøÎ, 7,7));


UPDATE EMPLOYEE
SET SSN1 = SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 7,7) , SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 7,7));
--==>> 1 «‡ ¿Ã(∞°) æ˜µ•¿Ã∆Æµ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM EMPLOYEE;
--==>> 1	æˆº“ø¨	?`??$?	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?

-- ®Á-3. ±‚¡∏ SSN(¡÷πŒπ¯»£) ƒ√∑≥ ¡¶∞≈
ALTER TABLE EMPLOYEE
DROP COLUMN SSN;
--==>> Table EMPLOYEE¿Ã(∞°) ∫Ø∞Êµ«æ˙Ω¿¥œ¥Ÿ.



-- ®Ë-1. GRADE ƒ√∑≥ √ﬂ∞° °Ê ±‚∫ª∞™¿ª 1(¿œπ›ªÁø¯)∑Œ ±∏º∫ °⁄°⁄
ALTER TABLE EMPLOYEE
ADD GRADE NUMBER(1) DEFAULT 1;
--==>> Table EMPLOYEE¿Ã(∞°) ∫Ø∞Êµ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM EMPLOYEE;
--==>> 1	æˆº“ø¨	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	1

--®Ë-2. æˆº“ø¨ ªÁø¯¿ª ∞¸∏Æ¿⁄∑Œ ¿”∏Ì(º≥¡§)
UPDATE EMPLOYEE
SET GRADE = 0
WHERE EMPLOYEEID = 1;
--==>> 1 «‡ ¿Ã(∞°) æ˜µ•¿Ã∆Æµ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM EMPLOYEE;
--==>> 1	æˆº“ø¨	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0

--°€ ƒøπ‘
COMMIT;
--==>> ƒøπ‘ øœ∑·.


-- °ÿ ≈◊¿Ã∫Ì¿« ±∏¡∂∏¶ ∫Ø∞Ê«ﬂ±‚ ãöπÆø°
--  ¿Ã ≈◊¿Ã∫Ì(EMPLOYEE)¿ª ±‚π›¿∏∑Œ ª˝º∫«— ∫‰¿« ≥ªøÎ¿ª ºˆ¡§
CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN1 AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, 'æÁ∑¬', 1, '¿Ω∑¬') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID = E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
    , E.GRADE AS GRADE
FROM EMPLOYEE E;
--==>> View EMPLOYEEVIEW¿Ã(∞°) ª˝º∫µ«æ˙Ω¿¥œ¥Ÿ.

SELECT *
FROM EMPLOYEEVIEW;
--==>> 1	æˆº“ø¨	941124	1994-11-24	0	æÁ∑¬	010-7193-4562	1	∞≥πﬂ∫Œ	1	ªÁø¯	1	º≠øÔ


--°€ µ•¿Ã≈Õ ¿‘∑¬ (¡˜ø¯ µ•¿Ã≈Õ ¿‘∑¬) - ƒ√∑≥¿« ±∏¡∂∞° ∫Ø∞Êµ» ªÁ«◊¿ª ±‚π›¿∏∑Œ ¥ŸΩ√ ±∏º∫~!!
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN1, SSN2, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'¡§πÃ∞Ê','981009', CRYPTPACK.ENCRYPT('2345678', '2345678')
        , TO_DATE('1998-10-09','YYYY-MM-DD'),0,'010-3098-8091', 1, 1, 8, 1500000, 1500000 );
--==>> 1 «‡ ¿Ã(∞°) ª¿‘µ«æ˙Ω¿¥œ¥Ÿ.



INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN1, SSN2, BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY) VALUES ( EMPLOYEESEQ.NEXTVAL,'¡§πÃ∞Ê','981009', CRYPTPACK.ENCRYPT('2345678', '2345678'), TO_DATE('1998-10-09','YYYY-MM-DD'),0,'010-3098-8091', 1, 1, 8, 1500000, 1500000 )
;

ROLLBACK;

SELECT *
FROM EMPLOYEE;
/*
1	æˆº“ø¨	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0
2	¡§πÃ∞Ê	1998-10-09	0	010-3098-8091	1	1	8	1500000	1500000	981009	?r??o	1
*/
SELECT *
FROM EMPLOYEEVIEW;
/*
1	æˆº“ø¨	941124	1994-11-24	0	æÁ∑¬	010-7193-4562	1	∞≥πﬂ∫Œ	1	ªÁø¯	1	º≠øÔ	1500000	1500000	3000000	0
2	¡§πÃ∞Ê	981009	1998-10-09	0	æÁ∑¬	010-3098-8091	1	∞≥πﬂ∫Œ	1	ªÁø¯	8	∞Ê±‚	1500000	1500000	3000000	1
*/

COMMIT;
--==>> ƒøπ‘ øœ∑·.


SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 1
;


--------------------------------------------------------------------------------

-- ¿œπ›ªÁø¯ ∑Œ±◊¿Œ ƒı∏ÆπÆ ±∏º∫(æ∆¿Ãµ, ∆–Ω∫øˆµÂ)
-- ªÁø¯π¯»£, ¡÷πŒπ¯»£µﬁ¿⁄∏Æ
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = æ∆¿Ãµ
 AND SSN2= ∆–Ω∫øˆµÂ;

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
 AND SSN2 =CRYPTPACK.ENCRYPT('2345678', '2345678');
--==>> ¡§πÃ∞Ê
--> ¿œπ›ªÁø¯¿∏∑Œ ∑Œ±◊¿Œ º∫∞¯~!!

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
 AND SSN2 =CRYPTPACK.ENCRYPT('1234567', '1234567');
--==>> ¡∂»∏ ∞·∞˙ æ¯¿Ω
--> ¿œπ›ªÁø¯¿∏∑Œ ∑Œ±◊¿Œ Ω«∆– ~!!! ∫Òπ¯ ∆≤∏≤

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('2234567', '2234567');
--==>> æˆº“ø¨
--> ¿œπ›ªÁø¯¿∏∑Œ ∑Œ±◊¿Œ º∫∞¯~!!

-- ¿œπ›ªÁø¯ ∑Œ±◊¿Œ ƒ˚∏ÆπÆ «— ¡Ÿ ±∏º∫
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 'IDπÆ¿⁄ø≠' AND SSN2 =CRYPTPACK.ENCRYPT('PWπÆ¿⁄ø≠', 'PWπÆ¿⁄ø≠')
;


-- ∞¸∏Æ¿⁄ ∑Œ±◊¿Œ ƒı∏ÆπÆ ±∏º∫(æ∆¿Ãµ, ∆–Ω∫øˆµÂ, µÓ±ﬁ)
-- ªÁø¯π¯»£, ¡÷πŒπ¯»£µﬁ¿⁄∏Æ, µÓ±ﬁ
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = æ∆¿Ãµ
 AND SSN2 = ∆–Ω∫øˆµÂ
 AND GRADE = 0;

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('2345678', '2345678')
 AND GRADE = 0;
--==>> ¡∂»∏∞·∞˙ æ¯¿Ω
--> ∞¸∏Æ¿⁄∑Œ ∑Œ±◊¿Œ Ω«∆–~!!

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('123', '123')
 AND GRADE = 0;
--=>> æˆº“ø¨
--> ∞¸∏Æ¿⁄∑Œ ∑Œ±◊¿Œ º∫∞¯~!!

-- ∞¸∏Æ¿⁄ ∑Œ±◊¿Œ ƒ˚∏ÆπÆ «— ¡Ÿ ±∏º∫
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 'πÆ¿⁄ø≠ID' AND SSN2 =CRYPTPACK.ENCRYPT('PWπÆ¿⁄ø≠', 'PWπÆ¿⁄ø≠') AND GRADE = 0
 ;



-- ∫Òπ–π¯»£∞° ∏¬¿ª∞ÊøÏ1 æ∆¥œ∏È 0 
SELECT COUNT(*)AS COUNT
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
AND SSN2= CRYPTPACK.ENCRYPT(2234565, 2234565);

SELECT COUNT(*)AS COUNT
FROM EMPLOYEE
WHERE EMPLOYEEID = 7
AND SSN2= CRYPTPACK.ENCRYPT(1111111, 1111111);


-->  «— ¡Ÿ ±∏º∫
SELECT COUNT(*) AS COUNT FROM EMPLOYEE WHERE EMPLOYEEID = 1 AND SSN2= CRYPTPACK.ENCRYPT(123, 123)
;

-- ¿œπ› ¡˜ø¯¿« ¡˜ø¯ ∏ÆΩ∫∆Æ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE
    , DEPARTMENTNAME, POSITIONNAME, REGIONNAME
FROM EMPLOYEEVIEW
ORDER BY EMPLOYEEID;

-- «— ¡Ÿ ±∏º∫
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE , DEPARTMENTNAME, POSITIONNAME, REGIONNAME FROM EMPLOYEEVIEW ORDER BY EMPLOYEEID
;


-- ¿œπ›¡˜ø¯¿« ¡ˆø™ ∏ÆΩ∫∆Æ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫

SELECT REGIONID, REGIONNAME 
FROM REGIONVIEW
ORDER BY REGIONID;

--> «— ¡Ÿ ±∏º∫
SELECT REGIONID, REGIONNAME FROM REGIONVIEW ORDER BY REGIONID
;

-- ¿œπ›¡˜ø¯¿« ∫Œº≠ ∏ÆΩ∫∆Æ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT DEPARTMENTID, DEPARTMENTNAME 
FROM DEPARTMENTVIEW
ORDER BY DEPARTMENTID;

--> «— ¡Ÿ ±∏º∫
SELECT DEPARTMENTID, DEPARTMENTNAME FROM DEPARTMENTVIEW ORDER BY DEPARTMENTID
;

-- ¿œπ›¡˜ø¯¿« ¡˜¿ß ∏ÆΩ∫∆Æ ¡∂»∏ ƒı∏ÆπÆ ±∏º∫
SELECT POSITIONID, POSITIONNAME
FROM POSITIONVIEW
ORDER BY POSITIONID;
--> «— ¡Ÿ ±∏º∫

SELECT POSITIONID, POSITIONNAME FROM POSITIONVIEW ORDER BY POSITIONID
;
---------------------------------------------------------------------------------
DESC EMPLOYEEVIEW;

DESC DEPARTMENTVIEW;

DESC EMPLOYEE;

DESC REGIONVIEW;

DESC POSITIONVIEW;
























