SELECT USER
FROM DUAL;
--==>> SCOTT

--○ 기존 테이블 제거
DROP TABLE TBL_MEMBERLIST PURGE;
--==>> Table TBL_MEMBERLIST이(가) 삭제되었습니다.

SELECT *
FROM TBL_MEMBERLIST;

--○ 실습 테이블 다시 생성
CREATE TABLE TBL_MEMBERLIST
( MID   NUMBER
, NAME  VARCHAR2(30)
, TELEPHONE VARCHAR2(50)
, CONSTRAINT MEMBERLIST_MID_PK PRIMARY KEY(MID)
);
--==>> Table TBL_MEMBERLSIT이(가) 생성되었습니다.

SELECT *
FROM TAB;
--○ 시퀀스 생성
CREATE SEQUENCE MEMBERLISTSEQ
NOCACHE;
--==>>Sequence MEMBERLISTSEQ이(가) 생성되었습니다.

DROP SEQUENCE MEMBERLISTSEQ;

--○샘플 데이터 입력
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE)
VALUES (MEMBERLISTSEQQ.NEXTVAL, '박원석', '010-1111-1111');
--> 한줄 구성

INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) VALUES (MEMBERLISTSEQ.NEXTVAL, '박원석', '010-1111-1111')
;

INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) VALUES (MEMBERLISTSEQ.NEXTVAL, '엄소연', '010-2222-2222')
;

SELECT *
FROM TBL_MEMBERLIST;

/*
1	박원석	010-1111-1111
3	엄소연	010-2222-2222
*/

--○ 인원 수 조회
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;

--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_MEMBERLIST
;

--○ 멤버 목록 (리스트) 조회 쿼리문
SELECT MID, NAME, TELEPHONE
FROM TBL_MEMBERLIST
ORDER BY MID;

--> 한 줄 구성
SELECT MID, NAME, TELEPHONE FROM TBL_MEMBERLIST ORDER BY MID
;

COMMIT;
--==>> 커밋 완료.











