SELECT USER
FROM DUAL;
--==>> SCOTT 2022-11-15

--¡Û ½Ç½À Å×ÀÌºí »ý¼º (Áö¿ª:REGION)
CREATE TABLE REGION
( REGIONID  NUMBER                  -- Áö¿ª ¾ÆÀÌµð   - PK
, REGIONNAME VARCHAR2(30)           -- Áö¿ª ÀÌ¸§
, CONSTRAINT REGION_ID_PK PRIMARY KEY(REGIONID)
);
--==>>Table REGIONÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û½ÃÄö½º »ý¼º
CREATE SEQUENCE REGIONSEQ
NOCACHE;
--==>> Sequence REGIONSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (Áö¿ª µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¼­¿ï');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'ÀÎÃµ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'´ë±¸');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'±¤ÁÖ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'´ëÀü');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'ºÎ»ê');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'¿ï»ê');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'°æ±â');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'°­¿ø');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'ÃæºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'Ãæ³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'ÀüºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'Àü³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'°æºÏ');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'°æ³²');
INSERT INTO REGION(REGIONID, REGIONNAME) VALUES(REGIONSEQ.NEXTVAL,'Á¦ÁÖ');
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù. * 16

--¡Û È®ÀÎ
SELECT REGIONID, REGIONNAME
FROM REGION;
/*
1	¼­¿ï
2	ÀÎÃµ
3	´ë±¸
4	±¤ÁÖ
5	´ëÀü
6	ºÎ»ê
7	¿ï»ê
8	°æ±â
9	°­¿ø
10	ÃæºÏ
11	Ãæ³²
12	ÀüºÏ
13	Àü³²
14	°æºÏ
15	°æ³²
16	Á¦ÁÖ
*/
--¡Û Ä¿¹Ô
COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.

--¡Û ½Ç½À Å×ÀÌºí »ý¼º(Á÷À§ : POSITION)
CREATE TABLE POSITION
( POSITIONID    NUMBER          -- Á÷À§ ¾ÆÀÌµð -- pk
, POSITIONNAME  VARCHAR2(30)    -- Á÷À§ ÀÌ¸§
, MINBASICPAY   NUMBER          -- ÇØ´ç Á÷À§ÀÇ ÃÖ¼Ò ±âº»±Þ
, CONSTRAINT POSITION_ID_PK PRIMARY KEY(POSITIONID)
);
--==>> Table POSITIONÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û ½ÃÄö½º »ý¼º( Á÷À§ : POSITIONSEQ)
CREATE SEQUENCE POSITIONSEQ
NOCACHE;
--==>> Sequence POSITIONSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (Á÷À§ µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '»ç¿ø', 1000000); -- ¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '´ë¸®', 2000000); -- ÀÌ¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '°úÀå', 3000000); -- »ï¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, 'ºÎÀå', 4000000); -- »ç¹é¸¸
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY)
VALUES(POSITIONSEQ.NEXTVAL, '»ó¹«', 5000000); -- ¿À¹é¸¸
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù. * 5

--¡Û È®ÀÎ
SELECT POSITIONID, POSITIONNAME, MINBASICPAY
FROM POSITION;
/*
1	»ç¿ø	1000000
2	´ë¸®	2000000
3	°úÀå	3000000
4	ºÎÀå	4000000
5	»ó¹«	5000000
*/

--¡Û Ä¿¹Ô
COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.

-- Á÷À§ µ¥ÀÌÅÍ ÀÔ·Â
INSERT INTO POSITION(POSITIONID, POSITIONNAME, MINBASICPAY) VALUES(POSITIONSEQ.NEXTVAL, '»ó¹«', 5000000)
;




--¡Û ½Ç½À Å×ÀÌºí »ý¼º(ºÎ¼­ : DEPARTMENT_
CREATE TABLE DEPARTMENT
( DEPARTMENTID  NUMBER              -- ºÎ¼­ ¾ÆÀÌµð   --PK
, DEPARTMENTNAME    VARCHAR2(30)    -- ºÎ¼­ ÀÌ¸§
, CONSTRAINT DEPARTMENT_ID_PK PRIMARY KEY(DEPARTMENTID)
);
--==>> Table DEPARTMENTÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


--¡Û½ÃÄö½º »÷¼º(ºÎ¼­ : DRPARTMENTSEQ)
CREATE SEQUENCE DEPARTMENTSEQ
NOCACHE;
--==>> Sequence DEPARTMENTSEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û µ¥ÀÌÅÍ ÀÔ·Â (ºÎ¼­ µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'°³¹ßºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'±âÈ¹ºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'¿µ¾÷ºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'ÀÎ»çºÎ');
INSERT INTO DEPARTMENT(DEPARTMENTID, DEPARTMENTNAME) VALUES(DEPARTMENTSEQ.NEXTVAL,'»ç¾÷ºÎ');
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù.


--¡Û È®ÀÎ
SELECT DEPARTMENTID, DEPARTMENTNAME
FROM DEPARTMENT;
/*
1	°³¹ßºÎ
2	±âÈ¹ºÎ
3	¿µ¾÷ºÎ
4	ÀÎ»çºÎ
5	»ç¾÷ºÎ
*/

--¡Û Ä¿¹Ô
COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.


--¡Û ½Ç½À Å×ÀÌºí »ý¼º(Á÷¿ø : EMPLOYEE)
-- »ç¿ø¹øÈ£, »ç¿ø¸í, ÁÖ¹Î¹øÈ£, »ý³â¿ùÀÏ, ¾çÀ½·Â, ÀüÈ­¹øÈ£, ºÎ¼­, Á÷À§, Áö¿ª, ±âº»±Þ, ¼ö´ç (11°³)
CREATE TABLE EMPLOYEE
( EMPLOYEEID    NUMBER              -- »ç¿ø ¹øÈ£     --PK
, NAME          VARCHAR2(30)        -- »ç¿ø ÀÌ¸§
, SSN           VARCHAR2(20)        -- ÁÖ¹Î ¹øÈ£        -- ¾ÏÈ£È­ ±â´É Àû¿ë(Å¸ÀÔ CHECK~!!)
, BIRTHDAY      DATE                -- »ý³â ¿ùÀÏ
, LUNAR         NUMBER(1) DEFAULT 0 -- ¾çÀ½·Â        -- ¾ç·Â0, À½·Â1
, TELEPHONE     VARCHAR2(40)        -- ÀüÈ­¹øÈ£
, DEPARTMENTID  NUMBER              -- ºÎ¼­ ¾ÆÀÌµð   -- FK
, POSITIONID    NUMBER              -- Á÷À§ ¾ÆÀÌµð   -- FK
, REGIONID      NUMBER              -- Áö¿ª ¾ÆÀÌµð   -- FK
, BASICPAY      NUMBER              -- ±âº»±Þ
, EXTRAPAY      NUMBER              -- ¼ö´ç
, CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYEEID)
, CONSTRAINT EMPLOYEE_DEPARMENTID_FK FOREIGN KEY(DEPARTMENTID)
            REFERENCES DEPARTMENT(DEPARTMENTID)
, CONSTRAINT EMPLOYEE_POSITION_FK FOREIGN KEY(POSITIONID)
            REFERENCES POSITION(POSITIONID)
, CONSTRAINT EMPLOYEE_REGIONID_FK FOREIGN KEY(REGIONID)
            REFERENCES REGION(REGIONID)
, CONSTRAINT EMPLOYEE_LUNAR_CK CHECK(LUNAR=0 OR LUNAR=1)

);
--==>> Table EMPLOYEEÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.



--¡Û ½ÃÄö½º »ý¼º
CREATE SEQUENCE EMPLOYEESEQ
NOCACHE;
--==>> Sequence EMPLOYEESEQÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.



--¡Û  µ¥ÀÌÅÍ ÀÔ·Â(Á÷¿ø µ¥ÀÌÅÍ ÀÔ·Â)
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'¾ö¼Ò¿¬', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567')
        , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000  );
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù.

INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY) VALUES ( EMPLOYEESEQ.NEXTVAL,'¾ö¼Ò¿¬', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567') , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000)
;



-- È®ÀÎ
SELECT *
FROM EMPLOYEE;
/*
EMPLOYEEID, NAME, SSN,     BIRTHDAY,  LUNAR, TELEPHONE,  DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY
----------------------------------------------------------------------------------------------------------
  1	     ¾ö¼Ò¿¬	 ?`??$?	1994-11-24	0	010-7193-4562	1       	1	          1	    1500000	   1500000
*/
-- Á÷¿ø Á¤º¸ ¼öÁ¤ Äõ¸®¹® ±¸¼º ¾î·Æ´Ù........


/* ¿Ï¼ºÇØº¸±â...,,
UPDATE EMPLOYEE
SET NAME = ¹Ýº¸¿µ, TO_CHAR(2022-11-11, 'YYYY-MM-DD), LUNAR = 0,TELEPHONE = 010-9999-9999, DEPARTMENTID=1
, POSITIONID = 1, REGIONID = 7, BASICPAY = 2000000, EXTRAPAY= 1500000, GRADE=1
WHERE EMPLOYEEID = 1;
*/



-- ¡Û Ä¿¹Ô
COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.

--¡Û Á÷¿ø Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID= E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;

--¡Û ºä »ý¼º (EMPLOYEEVIEW)
CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID= E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
FROM EMPLOYEE E;
--==>> View EMPLOYEEVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

--¡Û È®ÀÎ
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, LUNARNAME, TELEPHONE, DEPARTMENTID, DEPARTMENTNAME, POSITIONID, POSITIONNAME, REGIONID, REGIONNAME, BASICPAY, EXTRAPAY, PAY, GRADE FROM EMPLOYEEVIEW
;

-- Á÷¿ø µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º
DELETE
FROM EMPLOYEEVIEW
WHERE EMPLOYEEID = 1;

DELETE FROM EMPLOYEEVIEW WHERE EMPLOYEEID = 1
;






UPDATE EMPLOYEE
SET NAME = ? 
WHERE EMPLOYEEID=1;




SELECT * FROM EMPLOYEEVIEW
;
/*
1	¾ö¼Ò¿¬	?`??$?	1994-11-24	0	¾ç·Â	010-7193-4562	1	°³¹ßºÎ	1	»ç¿ø	1	¼­¿ï	1500000	1500000	3000000
*/

--¡Û Áö¿ª Á¤º¸ Á¶È¸ Äû¸®¹® ±¸¼º
--  (Æ¯Á¤ Áö¿ª µ¥ÀÌÅÍ »èÁ¦ °¡´É¿©ºÎ È®ÀÎ)
SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;
/*
1	¼­¿ï	1
2	ÀÎÃµ	0
    :
14	°æºÏ	0
15	°æ³²	0
16	Á¦ÁÖ	0
*/
--> ¡º¼­¿ï¡»ÀÇ Áö¿ª Á¤º¸¸¦ »èÁ¦°¡ ºÒ°¡´ÉÇÑ µ¥ÀÌÅÍÀÌ¸ç,
-- ±× ¿Ü ³ª¸ÓÁö Áö¿ª Á¤º¸´Â »èÁ¦°¡ °¡´ÉÇÑ µ¥ÀÌÅÍÀÓÀ» ÆÇº°ÇÒ ¼ö ÀÖ¶Ç·Ï ±¸¼ºÇÑ Äõ¸®¹®


--¡Ø ºä »ý¼º(Áö¿ª Á¤º¸ : REGIONVIEW)
CREATE OR REPLACE VIEW REGIONVIEW
AS
SELECT R.REGIONID AS REGIONID
    , R.REGIONNAME AS REGIONNAME
    , ( SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE REGIONID = R.REGIONID) AS DELCHECK
FROM REGION R;
--==>> View REGIONVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

SELECT REGIONID, REGIONNAME, DELCHECK
FROM REGIONVIEW;

SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW
;

--¡Û Á÷À§ Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
--  (Æ¯Á¤ Á÷À§ µ¥ÀÌÅÍ »èÁ¦ °¡´É¿©ºÎ È®ÀÎ)

SELECT P.POSITIONID AS POSITIONID
      , P.POSITIONNAME AS POSITIONNAME
      , P.MINBASICPAY AS MINBASICPAY
      ,( SELECT COUNT(*)
         FROM EMPLOYEE
         WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;


--¡Ø ºä »ý¼º(Áö¿ª Á¤º¸ : POSITIONVIEW)
CREATE OR REPLACE VIEW POSITIONVIEW
AS
SELECT P.POSITIONID AS POSITIONID
      , P.POSITIONNAME AS POSITIONNAME
      , P.MINBASICPAY AS MINBASICPAY
      ,( SELECT COUNT(*)
         FROM EMPLOYEE
         WHERE POSITIONID = P.POSITIONID) AS DELCHECK
FROM POSITION P;
--==>> View POSITIONVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

SELECT *
FROM POSITIONVIEW;

SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW
;


--¡Û ºÎ¼­ Á¤º¸ Á¶È¸ Äõ¸®¹® ±¸¼º
--  (Æ¯Á¤ ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦ °¡´É¿©ºÎ È®ÀÎ)

SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    , (SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;

--¡Ø ºä »ý¼º( Á¤º¸ : DEPARTMENTVIEW)
CREATE OR REPLACE VIEW DEPARTMENTVIEW
AS
SELECT D.DEPARTMENTID AS DEPARTMENTID
    , D.DEPARTMENTNAME AS DEPARTMENTNAME
    , (SELECT COUNT(*)
        FROM EMPLOYEE
        WHERE DEPARTMENTID = D.DEPARTMENTID) AS DELCHECK
FROM DEPARTMENT D;
--==>> View DEPARTMENTVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.


-- ºÎ¼­ ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK
FROM DEPARTMENTVIEW
ORDER BY DEPARTMENTID;
/*
1	°³¹ßºÎ	1
2	±âÈ¹ºÎ	0
3	¿µ¾÷ºÎ	0
4	ÀÎ»çºÎ	0
5	»ç¾÷ºÎ	0
*/

--> ÇÑÁÙ ±¸¼º
SELECT DEPARTMENTID, DEPARTMENTNAME, DELCHECK FROM DEPARTMENTVIEW ORDER BY DEPARTMENTID
;

--ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º (ºÎ¼­ ¹øÈ£·Î ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦)
DELETE
FROM DEPARTMENT
WHERE DEPARTMENTID = 1;
--> ÇÑÁÙ ±¸¼º
DELETE FROM DEPARTMENT WHERE DEPARTMENTID = 1
;
-- ºÎ¼­ µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® (ºÎ¼­ ¹øÈ£·Î ºÎ¼­ ÀÌ¸§ º¯°æ)
UPDATE DEPARTMENT
SET DEPARTMENTNAME = 'ÃÑ¹«ºÎ'
WHERE DEPARTMENTID = 1;

--> ÇÑÁÙ ±¸¼º

UPDATE DEPARTMENT SET DEPARTMENTNAME = 'ÃÑ¹«ºÎ' WHERE DEPARTMENTID = 1
;
--==>> 1 Çà ÀÌ(°¡) ¾÷µ¥ÀÌÆ®µÇ¾ú½À´Ï´Ù.


SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW ORDER BY REGIONID;

SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, LUNARNAME , TELEPHONE, DEPARTMENTID, DEPARTMENTNAME, POSITIONID , POSITIONNAME, REGIONID, REGIONNAME, BASICPAY, EXTRAPAY, PAY, GRADE FROM EMPLOYEEVIEW ORDER BY EMPLOYEEID
;

-- EMPLOYEE Å×ÀÌºí Á¶È¸ Äõ¸®¹®
SELECT EMPLOYEEID, NAME, SSN1, TO_CHAR(BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID , POSITIONID, REGIONID, BASICPAY, EXTRAPAY FROM EMPLOYEE WHERE EMPLOYEEID = 1
;


ROLLBACK;


-- Áö¿ª ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT REGIONID, REGIONNAME
FROM REGIONVIEW
ORDER BY REGIONID; 
/*
1	¼­¿ï
2	ÀÎÃµ
3	´ë±¸
4	±¤ÁÖ
5	´ëÀü
6	ºÎ»ê
7	¿ï»ê
8	°æ±â
9	°­¿ø
10	ÃæºÏ
11	Ãæ³²
12	ÀüºÏ
13	Àü³²
14	°æºÏ
15	°æ³²
16	Á¦ÁÖ
*/

SELECT REGIONID, REGIONNAME, DELCHECK FROM REGIONVIEW ORDER BY REGIONID
;


--Áö¿ª µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º (Áö¿ª ¹øÈ£·Î ºÎ¼­ µ¥ÀÌÅÍ »èÁ¦)
DELETE
FROM REGION
WHERE REGIONID = 1;
--> ÇÑÁÙ ±¸¼º
DELETE FROM REGION WHERE REGIONID = 1
;

--Áö¿ª µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® ±¸¼º (Áö¿ª ¹øÈ£¿À Áö¿ª ÀÌ¸§ º¯°æ)

UPDATE REGION
SET REGIONNAME = 'Áö¿ª¸í'
WHERE REGIONID = 1;
--> ÇÑÁÙ ±¸¼º

UPDATE REGION SET REGIONNAME = 'Áö¿ª¸í' WHERE REGIONID = 1
;
--==>> 1 Çà ÀÌ(°¡) ¾÷µ¥ÀÌÆ®µÇ¾ú½À´Ï´Ù.

ROLLBACK;
--==>> ·Ñ¹é ¿Ï·á.

-- Á÷À§ ÀüÃ¼ µ¥ÀÌÅÍ Á¶È¸ Äõ¸®¹® ±¸¼º

SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK
FROM POSITIONVIEW
ORDER BY POSITIONID;

--> ÇÑ ÁÙ ±¸¼º
SELECT POSITIONID, POSITIONNAME, MINBASICPAY, DELCHECK FROM POSITIONVIEW ORDER BY POSITIONID
;
/*
1	»ç¿ø	1000000	1
2	´ë¸®	2000000	0
3	°úÀå	3000000	0
4	ºÎÀå	4000000	0
5	»ó¹«	5000000	0
*/

--Á÷À§ µ¥ÀÌÅÍ »èÁ¦ Äõ¸®¹® ±¸¼º (Á÷À§ ¹øÈ£·Î Á÷À§ µ¥ÀÌÅÍ »èÁ¦)

DELETE
FROM POSITION
WHERE POSITIONID = 1;
--> ÇÑ ÁÙ ±¸¼º

DELETE FROM POSITION WHERE POSITIONID = 1
;

--Á÷À§ µ¥ÀÌÅÍ ¼öÁ¤ Äõ¸®¹® ±¸¼º (Á÷À§ ¹øÈ£·Î Á÷À§ ÀÌ¸§ º¯°æ)
   
UPDATE POSITION
SET POSITIONNAME = 'Á÷À§¸í'
    , MINBASICPAY = 300000
WHERE POSITIONID = 1;
--> ÇÑ ÁÙ ±¸¼º
UPDATE POSITION SET POSITIONNAME = 'Á÷À§¸í' , MINBASICPAY = 300000 WHERE POSITIONID = 1
;
--==> 1 Çà ÀÌ(°¡) ¾÷µ¥ÀÌÆ®µÇ¾ú½À´Ï´Ù.

ROLLBACK;
--==>> ·Ñ¹é ¿Ï·á.

SELECT MINBASICPAY
FROM POSITION
WHERE POSITIONID = 1;


SELECT MINBASICPAY FROM POSITION WHERE POSITIONID = 1
;



--------------------------------------------------------------------------------
--¡á¡á¡á ·Î±×ÀÎ/ ·Î±×¾Æ¿ô ±â´É Àû¿ë °úÁ¤ Ãß°¡¡á¡á¡á--

-- ÇöÀç ¿ì¸®°¡ ±¸¼ºÇÑ µ¥ÀÌºí ±¸Á¶´Â ID ¿Í PW ÄÃ·³ Á¤º¸¸¦ ´ã°íÀÖ´Â µ¥ÀÌºíÀÌ 
-- º°µµ·Î Á¸ÀçÇÏÁö ¾Ê´Â »óÈ²ÀÌ´Ù.
-- ÀÌ¿Í °ü·ÃÇÏ¿© EMPLOYEE(»ç¿ø ¾ÆÀÌµð)¿Í SSN(ÁÖ¹Î¹øÈ£) µÞÀÚ¸® 7ÀÚ¸®ÀÇ ¼ýÀÚ¸¦
-- È°¿ë¶ó¿© ±â´ÉÀ» ±¸ÇöÇÒ ¼ö ÀÖµµ·Ï Ã³¸®ÇÑ´Ù.

-- ¡Ø ±âÁ¸ µ¥ÀÌºí ±¸Á¶ º¯°æ °èÈ¹
-- ¨ç
-- EMPLOYEE (Á÷¿ø µ¥ÀÌÅÍ µ¥ÀÌºí) ÀÇ SSN(ÁÖ¹Î¹øÈ£) ÄÃ·³À» ºÐ¸®ÇÑ´Ù.
-- SSN   -------------> SSN1, SSN2
-- SSN1 --------------> ÁÖ¹Î¹øÈ£ ¾Õ 6ÀÚ¸®
-- SSN2 --------------> ÁÖ¹Î¹øÈ£ µÞ 7ÀÚ¸® ¡æ ¾ÏÈ£È­ Àû¿ë

--¨è
-- EMPLOYEE (Á÷¿ø µ¥ÀÌÅÍ µ¥ÀÌºí)ÀÇ GEADE(µî±Þ) ÄÃ·³À» Ãß°¡ÇÑ´Ù.
-- GRADE --------------> °ü¸®ÀÚ0, ÀÏ¹Ý»ç¿ø1


-- ¡Ø ±âÁ¸ µ¥ÀÌºí ±¸Á¶ º¯°æ ¼öÇà

--¨ç-1. ÄÃ·³ Ãß°¡
ALTER TABLE EMPLOYEE
ADD(SSN1 CHAR(6), SSN2 VARCHAR2(50));
--==>> Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;

-- ¨ç-2. ±âÁ¸ µ¥ÀÌÅÍ¿¡ ´ëÇØ ÄÃ·³ÀÇ ³»¿ë ¼öÁ¤
-- '9411242234567'
/*
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'¾ö¼Ò¿¬', CRYPTPACK.ENCRYPT('9411242234567', '9411242234567')
        , TO_DATE('1994-11-24','YYYY-MM-DD'),0,'010-7193-4562', 1, 1, 1, 1500000, 1500000  );
*/
---------------------------------³»°¡ ÇÑ °Í
UPDATE EMPLOYEE
SET SSN1 = SUBSTR(1,6)
WHERE SSN;

SELECT CRYPTPACK.DECRYPT('9411242234567','9411242234567')
FROM EMPLOYEE;

UPDATE EMPLOYEE
SET SSN1 = SUBSTR(SSN, 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(SSN, 7,7) , SUBSTR(SSN, 7,7));
WHERE SSN

----------------------------------------------- ¼±»ý´ÔÀÌ ÇÏ½Å°Í
SELECT CRYPTPACK.DECRYPT(SSN, '9411242234567')
FROM EMPLOYEE;
--==>>9411242234567

UPDATE EMPLOYEE
SET SSN1 = SUBSTR(ÀÔ·Â³»¿ë, 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(ÀÔ·Â³»¿ë, 7,7) , SUBSTR(ÀÔ·Â³»¿ë, 7,7));


UPDATE EMPLOYEE
SET SSN1 = SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 1,6)
  , SSN2 = CRYPTPACK.ENCRYPT(SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 7,7) , SUBSTR(CRYPTPACK.DECRYPT(SSN, '9411242234567'), 7,7));
--==>> 1 Çà ÀÌ(°¡) ¾÷µ¥ÀÌÆ®µÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;
--==>> 1	¾ö¼Ò¿¬	?`??$?	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?

-- ¨ç-3. ±âÁ¸ SSN(ÁÖ¹Î¹øÈ£) ÄÃ·³ Á¦°Å
ALTER TABLE EMPLOYEE
DROP COLUMN SSN;
--==>> Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.



-- ¨è-1. GRADE ÄÃ·³ Ãß°¡ ¡æ ±âº»°ªÀ» 1(ÀÏ¹Ý»ç¿ø)·Î ±¸¼º
ALTER TABLE EMPLOYEE
ADD GRADE NUMBER(1) DEFAULT 1;
--==>> Table EMPLOYEEÀÌ(°¡) º¯°æµÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;
--==>> 1	¾ö¼Ò¿¬	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	1

--¨è-2. ¾ö¼Ò¿¬ »ç¿øÀ» °ü¸®ÀÚ·Î ÀÓ¸í(¼³Á¤)
UPDATE EMPLOYEE
SET GRADE = 0
WHERE EMPLOYEEID = 1;
--==>> 1 Çà ÀÌ(°¡) ¾÷µ¥ÀÌÆ®µÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEE;
--==>> 1	¾ö¼Ò¿¬	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0

--¡Û Ä¿¹Ô
COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.


-- ¡Ø Å×ÀÌºíÀÇ ±¸Á¶¸¦ º¯°æÇß±â ‹š¹®¿¡
--  ÀÌ Å×ÀÌºí(EMPLOYEE)À» ±â¹ÝÀ¸·Î »ý¼ºÇÑ ºäÀÇ ³»¿ëÀ» ¼öÁ¤
CREATE OR REPLACE VIEW EMPLOYEEVIEW
AS
SELECT E.EMPLOYEEID AS EMPLOYEEID
     , E.NAME AS NAME
     , E.SSN1 AS SSN
     , TO_CHAR(E.BIRTHDAY, 'YYYY-MM-DD') AS BIRTHDAY
     , E.LUNAR AS LUNAR
     , DECODE(E.LUNAR, 0, '¾ç·Â', 1, 'À½·Â') AS LUNARNAME
     , E.TELEPHONE AS TELEPHONE
     , E.DEPARTMENTID AS DEPARTMENTID
     , (SELECT DEPARTMENTNAME
        FROM DEPARTMENT
        WHERE DEPARTMENTID = E.DEPARTMENTID) AS DEPARTMENTNAME
    , E.POSITIONID AS POSITIONID
    , (SELECT POSITIONNAME
       FROM POSITION
       WHERE POSITIONID = E.POSITIONID) AS POSITIONNAME
    , E.REGIONID AS REGIONID
    , (SELECT REGIONNAME
       FROM REGION
       WHERE REGIONID = E.REGIONID) AS REGIONNAME
    , E.BASICPAY AS BASICPAY
    , E.EXTRAPAY AS EXTRAPAY
    , NVL(E.BASICPAY, 0) + NVL(E.EXTRAPAY, 0) AS PAY
    , E.GRADE AS GRADE
FROM EMPLOYEE E;
--==>> View EMPLOYEEVIEWÀÌ(°¡) »ý¼ºµÇ¾ú½À´Ï´Ù.

SELECT *
FROM EMPLOYEEVIEW;
--==>> 1	¾ö¼Ò¿¬	941124	1994-11-24	0	¾ç·Â	010-7193-4562	1	°³¹ßºÎ	1	»ç¿ø	1	¼­¿ï


--¡Û µ¥ÀÌÅÍ ÀÔ·Â (Á÷¿ø µ¥ÀÌÅÍ ÀÔ·Â) - ÄÃ·³ÀÇ ±¸Á¶°¡ º¯°æµÈ »çÇ×À» ±â¹ÝÀ¸·Î ´Ù½Ã ±¸¼º~!!
INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN1, SSN2, BIRTHDAY, LUNAR, TELEPHONE
                   , DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY)
VALUES ( EMPLOYEESEQ.NEXTVAL,'Á¤¹Ì°æ','981009', CRYPTPACK.ENCRYPT('2345678', '2345678')
        , TO_DATE('1998-10-09','YYYY-MM-DD'),0,'010-3098-8091', 1, 1, 8, 1500000, 1500000 );
--==>> 1 Çà ÀÌ(°¡) »ðÀÔµÇ¾ú½À´Ï´Ù.



INSERT INTO EMPLOYEE(EMPLOYEEID, NAME, SSN1, SSN2, BIRTHDAY, LUNAR, TELEPHONE, DEPARTMENTID, POSITIONID, REGIONID, BASICPAY, EXTRAPAY) VALUES ( EMPLOYEESEQ.NEXTVAL,'Á¤¹Ì°æ','981009', CRYPTPACK.ENCRYPT('2345678', '2345678'), TO_DATE('1998-10-09','YYYY-MM-DD'),0,'010-3098-8091', 1, 1, 8, 1500000, 1500000 )
;

ROLLBACK;

SELECT *
FROM EMPLOYEE;
/*
1	¾ö¼Ò¿¬	1994-11-24	0	010-7193-4562	1	1	1	1500000	1500000	941124	Y{?7?	0
2	Á¤¹Ì°æ	1998-10-09	0	010-3098-8091	1	1	8	1500000	1500000	981009	?r??o	1
*/
SELECT *
FROM EMPLOYEEVIEW;
/*
1	¾ö¼Ò¿¬	941124	1994-11-24	0	¾ç·Â	010-7193-4562	1	°³¹ßºÎ	1	»ç¿ø	1	¼­¿ï	1500000	1500000	3000000	0
2	Á¤¹Ì°æ	981009	1998-10-09	0	¾ç·Â	010-3098-8091	1	°³¹ßºÎ	1	»ç¿ø	8	°æ±â	1500000	1500000	3000000	1
*/

COMMIT;
--==>> Ä¿¹Ô ¿Ï·á.


SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 1
;


--------------------------------------------------------------------------------

-- ÀÏ¹Ý»ç¿ø ·Î±×ÀÎ Äõ¸®¹® ±¸¼º(¾ÆÀÌµð, ÆÐ½º¿öµå)
-- »ç¿ø¹øÈ£, ÁÖ¹Î¹øÈ£µÞÀÚ¸®
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = ¾ÆÀÌµð
 AND SSN2= ÆÐ½º¿öµå;

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
 AND SSN2 =CRYPTPACK.ENCRYPT('2345678', '2345678');
--==>> Á¤¹Ì°æ
--> ÀÏ¹Ý»ç¿øÀ¸·Î ·Î±×ÀÎ ¼º°ø~!!

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 2
 AND SSN2 =CRYPTPACK.ENCRYPT('1234567', '1234567');
--==>> Á¶È¸ °á°ú ¾øÀ½
--> ÀÏ¹Ý»ç¿øÀ¸·Î ·Î±×ÀÎ ½ÇÆÐ ~!!! ºñ¹ø Æ²¸²

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('2234567', '2234567');
--==>> ¾ö¼Ò¿¬
--> ÀÏ¹Ý»ç¿øÀ¸·Î ·Î±×ÀÎ ¼º°ø~!!

-- ÀÏ¹Ý»ç¿ø ·Î±×ÀÎ Äû¸®¹® ÇÑ ÁÙ ±¸¼º
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = 'ID¹®ÀÚ¿­' AND SSN2 =CRYPTPACK.ENCRYPT('PW¹®ÀÚ¿­', 'PW¹®ÀÚ¿­')
;


-- °ü¸®ÀÚ ·Î±×ÀÎ Äõ¸®¹® ±¸¼º(¾ÆÀÌµð, ÆÐ½º¿öµå, µî±Þ)
-- »ç¿ø¹øÈ£, ÁÖ¹Î¹øÈ£µÞÀÚ¸®, µî±Þ
SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = ¾ÆÀÌµð
 AND SSN2 = ÆÐ½º¿öµå
 AND GRADE = 0;

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('2345678', '2345678')
 AND GRADE = 0;
--==>> Á¶È¸°á°ú ¾øÀ½
--> °ü¸®ÀÚ·Î ·Î±×ÀÎ ½ÇÆÐ~!!

SELECT NAME
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
 AND SSN2 =CRYPTPACK.ENCRYPT('123', '123')
 AND GRADE = 0;
--=>> ¾ö¼Ò¿¬
--> °ü¸®ÀÚ·Î ·Î±×ÀÎ ¼º°ø~!!

-- °ü¸®ÀÚ ·Î±×ÀÎ Äû¸®¹® ÇÑ ÁÙ ±¸¼º
SELECT NAME FROM EMPLOYEE WHERE EMPLOYEEID = '¹®ÀÚ¿­ID' AND SSN2 =CRYPTPACK.ENCRYPT('PW¹®ÀÚ¿­', 'PW¹®ÀÚ¿­') AND GRADE = 0
 ;



-- ºñ¹Ð¹øÈ£°¡ ¸ÂÀ»°æ¿ì1 ¾Æ´Ï¸é 0 
SELECT COUNT(*)AS COUNT
FROM EMPLOYEE
WHERE EMPLOYEEID = 1
AND SSN2= CRYPTPACK.ENCRYPT(2234565, 2234565);

SELECT COUNT(*)AS COUNT
FROM EMPLOYEE
WHERE EMPLOYEEID = 7
AND SSN2= CRYPTPACK.ENCRYPT(1111111, 1111111);


-->  ÇÑ ÁÙ ±¸¼º
SELECT COUNT(*) AS COUNT FROM EMPLOYEE WHERE EMPLOYEEID = 1 AND SSN2= CRYPTPACK.ENCRYPT(123, 123)
;

-- ÀÏ¹Ý Á÷¿øÀÇ ¸®½ºÆ® Á¶È¸ Äõ¸®¹® ±¸¼º
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE
    , DEPARTMENTNAME, POSITIONNAME, REGIONNAME
FROM EMPLOYEEVIEW
ORDER BY EMPLOYEEID;

-- ÇÑ ÁÙ ±¸¼º
SELECT EMPLOYEEID, NAME, SSN, BIRTHDAY, LUNARNAME, TELEPHONE , DEPARTMENTNAME, POSITIONNAME, REGIONNAME FROM EMPLOYEEVIEW ORDER BY EMPLOYEEID
;




---------------------------------------------------------------------------------
DESC EMPLOYEEVIEW;

DESC DEPARTMENTVIEW;

DESC EMPLOYEE;

DESC REGIONVIEW;



























